# This is a basic workflow to help you get started with Actions

name: Test action

# Controls when the workflow will run
on:
  schedule:
    - cron: 30 18 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs script
      - name: Make raw directory
        working-directory: data/
        run: |
          mkdir raw/

      - name: curl
        uses: wei/curl@master
        with:
          args: -s --insecure -L --compressed -o raw/bath_and_north_east_somerset_council.html "https://livewell.bathnes.gov.uk/warm-places-map"


      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: |
            JSON::XS
            Web::Scraper

      # Runs script
      - name: Run build script
        working-directory: data/
        run: |
          curl -s --insecure -L --compressed -o raw/bath_and_north_east_somerset_council.html "https://livewell.bathnes.gov.uk/warm-places-map"
          perl scrapers/bath_and_north_east_somerset_council.pl raw/bath_and_north_east_somerset_council.html
